version: "3.9"

services:
  quarkus-mysql:
    image: mysql:8.0
    container_name: quarkus-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: quarkus_db
      MYSQL_USER: quarkus_user
      MYSQL_PASSWORD: quarkus_pass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-u", "quarkus_user", "-pquarkus_pass", "-e", "SELECT 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 40s
    networks:
      - app-network

  zeebe:
    image: camunda/zeebe:8.5.0
    container_name: zeebe
    restart: always
    environment:
      ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_MODE: none
    ports:
      - "26500:26500"
      - "9600:9600"
    healthcheck:
      test: ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/26500' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s
    networks:
      - app-network

  ms-book-api:
    build: .
    container_name: ms-book-api
    restart: always
    depends_on:
      quarkus-mysql:
        condition: service_healthy
      zeebe:
        condition: service_healthy
    environment:
      # =========================
      # DATABASE
      # =========================
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://quarkus-mysql:3306/quarkus_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      QUARKUS_DATASOURCE_USERNAME: quarkus_user
      QUARKUS_DATASOURCE_PASSWORD: quarkus_pass

      # =========================
      # ZEEBE
      # =========================
      ZEEBE_CLIENT_BROKER_GATEWAY_ADDRESS: zeebe:26500
      ZEEBE_CLIENT_SECURITY_PLAINTEXT: "true"

      # =========================
      # APLICAÇÃO
      # =========================
      PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge